# Discover the locally installed Windows dependencies without overriding user hints.
if(NOT CMAKE_HOST_WIN32)
  return()
endif()

set(CMAKE_INSTALL_PREFIX "${CMAKE_SOURCE_DIR}/compiles" CACHE PATH "Server installation directory")
set(TOOLS ON CACHE BOOL "Build client data extractors")

if(NOT BOOST_ROOT AND NOT DEFINED ENV{BOOST_ROOT})
  file(GLOB _legion_boost_roots "$ENV{SystemDrive}/local/boost_*")
  list(SORT _legion_boost_roots COMPARE NATURAL)
  foreach(_root IN LISTS _legion_boost_roots)
    file(GLOB _legion_boost_system "${_root}/lib64-msvc-14.3/cmake/boost_system-*")
    if(_legion_boost_system)
      set(BOOST_ROOT "${_root}" CACHE PATH "Boost installation")
      break()
    endif()
  endforeach()
endif()

if(NOT OPENSSL_ROOT_DIR AND NOT DEFINED ENV{OPENSSL_ROOT_DIR})
  if(EXISTS "$ENV{ProgramFiles}/OpenSSL-Win64/include/openssl/ssl.h")
    set(OPENSSL_ROOT_DIR "$ENV{ProgramFiles}/OpenSSL-Win64" CACHE PATH "OpenSSL installation")
  endif()
endif()

if(NOT MYSQL_ROOT_DIR AND NOT DEFINED ENV{MYSQL_ROOT_DIR})
  file(GLOB _legion_mysql_roots "$ENV{SystemDrive}/wamp64/bin/mysql/mysql5.7.*")
  list(SORT _legion_mysql_roots COMPARE NATURAL ORDER DESCENDING)
  foreach(_root IN LISTS _legion_mysql_roots)
    if(EXISTS "${_root}/include/mysql.h" AND EXISTS "${_root}/lib/libmysql.lib")
      set(MYSQL_ROOT_DIR "${_root}" CACHE PATH "MySQL client SDK")
      break()
    endif()
  endforeach()
endif()

if(NOT MYSQL_EXECUTABLE)
  file(GLOB _legion_mariadb_clients "$ENV{SystemDrive}/wamp64/bin/mariadb/*/bin/mariadb.exe")
  list(SORT _legion_mariadb_clients COMPARE NATURAL ORDER DESCENDING)
  if(_legion_mariadb_clients)
    list(GET _legion_mariadb_clients 0 _legion_mariadb_client)
    set(MYSQL_EXECUTABLE "${_legion_mariadb_client}" CACHE FILEPATH "Database update client")
  endif()
endif()
